/* activate_partynpc.tpa */



COPY_EXISTING ~bdrom01.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom02.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom03.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom03.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom04.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom05.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom06.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom07.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom08.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom09.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom10.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom11.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom12.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom13.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom14.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom15.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom16.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom17.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES

COPY_EXISTING ~bdrom18.bcs~ ~override~
DECOMPILE_AND_PATCH BEGIN
REPLACE_TEXTUALLY ~\(IsOverMe(Player1)\)~
~OR(6)
\1 
IsOverMe(Player2)
IsOverMe(Player3)
IsOverMe(Player4)
IsOverMe(Player5)
IsOverMe(Player6)~
END
BUT_ONLY_IF_IT_CHANGES


EXTEND_BOTTOM ~bdcorwin.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bdcorwin.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~bddorn.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bddorn.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~bdglint.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bdglint.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~bdneera.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bdneera.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~bdrasaad.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bdrasaad.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~bdsafana.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bdsafana.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~bdviconi.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bdviconi.baf~ EVALUATE_BUFFER
EXTEND_BOTTOM ~bdvoghil.bcs~ ~c#sodtweaks/MissedDialogues/c#st_bdvoghil.baf~ EVALUATE_BUFFER

